src/INV/Models/Invention.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace INV.Models
{
    public class Invention 
    {

        public int ID { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Title cannot be longer than 100 characters.")]
        [Display(Name = "Invention Title")]
        public string Title { get; set; }
        [Display(Name = "Valuation")]
        [DataType(DataType.Currency)]
        public decimal Valuation { get; set; }
        //Once it is for sale, list it on inventions for sale
        [Display(Name = "Is Invention for Sale?")]
        public Boolean IsForSale { get; set; }
        [Display(Name = "Is Open for Funding?")]
        public Boolean IsOpenForFunding {
            get; set;
        }

        

        public ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }
        [Display(Name = "Is Published?")]
        public Boolean IsPublished { get; set; }
        [Column(TypeName = "ntext")]
        [Display(Name = "Plan to Refine then Sell")]
        public string LongDescription { get; set; }
        public ICollection<InvestmentRound> InvestmentRounds { get; set; }
        [Display(Name = "Date Created")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}")]
        public DateTime DateCreated { get; set; } = DateTime.Now;
    }


}

src/INV/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using INV.Data;
using INV.Models;
using System.Security.Claims;

namespace INV.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationUsersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.ToListAsync());
        }

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string user = "";
            if (User.Identity.Name != null)
            {
                user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            ApplicationUser applicationUser = await _context
                .ApplicationUser
                .Include(au => au.Inventions)
                .Include(au => au.Investments)
                .Include(au => au.ExpertServices)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (id == user)
            {
                ViewData["isEditable"] = "true";
                
            }
  

            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AccessFailedCount,ConcurrencyStamp,Email,EmailConfirmed,LinkedInURL,LockoutEnabled,LockoutEnd,LongDescription,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwitterURL,TwoFactorEnabled,UserName,WebAddress,YouTubeIntro,FirstName,LastName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                applicationUser.NormalizedEmail = applicationUser.Email; 
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AccessFailedCount,ConcurrencyStamp,Email,EmailConfirmed,LinkedInURL,LockoutEnabled,LockoutEnd,LongDescription,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwitterURL,TwoFactorEnabled,UserName,WebAddress,YouTubeIntro,FirstName,LastName")] ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    applicationUser.NormalizedEmail = applicationUser.Email;
                    _context.Update(applicationUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { Id = id });
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

src/INV/Controllers/ExpertServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using INV.Data;
using INV.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using System.Security.Claims;

namespace INV.Controllers
{
    public class ExpertServicesController : Controller
    {
        IAuthorizationService _authorizationService;
        private readonly ApplicationDbContext _context;

        private void PopulateServiceTypeDropDownList(object selectedServiceType = null)
        {
            ViewBag.ServiceTypeID = new SelectList(_context.ServiceType.OrderBy(i => i.Title).AsNoTracking(), "ID", "Title", selectedServiceType);

        }
 
        public ExpertServicesController(ApplicationDbContext context, IAuthorizationService authorizationService)
        {
            _context = context;
            _authorizationService = authorizationService;
        }

        // GET: ExpertServices
        public async Task<IActionResult> Index()
        {
            var expertServices = _context.ExpertService
                .Include(es => es.ServiceType)
                .Include(es => es.ApplicationUser)
                .AsNoTracking();
            ViewData["Title"] = "Browse All Experts";

            return View(await expertServices.ToListAsync());
        }

        // GET: PatentServices
        public async Task<IActionResult> Patent()
        {
            var expertServices = _context.ExpertService
                .Include(es => es.ServiceType)
                .Include(es=>es.ApplicationUser)
                .Where(es => es.ServiceType.Title == "Patent")
                .AsNoTracking();
            ViewData["Title"] = "Find a Patent Attorney";

            return View("Index", await expertServices.ToListAsync());
        }

        // GET: PrototypeServices
        public async Task<IActionResult> Prototype()
        {
            var expertServices = _context.ExpertService
                .Include(es => es.ServiceType)
                .Include(es => es.ApplicationUser)
                .Where(es => es.ServiceType.Title == "Prototype")
                .AsNoTracking();
            ViewData["Title"] = "Find a Prototype Builder";

            return View("Index", await expertServices.ToListAsync());
        }
        [Authorize]
        // GET: ExpertServices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expertService = await _context.ExpertService.Include(m => m.ServiceType).Include(m=>m.ApplicationUser).SingleOrDefaultAsync(m => m.ID == id);
            if (expertService == null)
            {
                return NotFound();
            }
            ViewData["isEditable"] = "false";
            if (expertService.ApplicationUserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                ViewData["isEditable"] = "true";
            }
            return View(expertService);
        }

        // GET: ExpertServices/Create
        [Authorize]
        public IActionResult Create()
        {
            PopulateServiceTypeDropDownList();
            return View();
        }

        public IActionResult CreatePatent()
        {
            PopulateServiceTypeDropDownList(1);
            return View("Create");
        }
        public IActionResult CreatePrototype()
        {
            PopulateServiceTypeDropDownList(2);
            return View("Create");
        }
        public IActionResult CreateOther()
        {
            PopulateServiceTypeDropDownList(3);
            return View("Create");
        }

        // POST: ExpertServices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,Cost,MaxDaysToComplete,ServiceTypeID,Title,LongDescription,IsPublished")] ExpertService expertService)
        {
            if (ModelState.IsValid)
            {
                var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                expertService.ApplicationUserId = user;
                _context.Add(expertService);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            PopulateServiceTypeDropDownList(expertService.ServiceType);
            return View(expertService);
        }

        // GET: ExpertServices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expertService = await _context.ExpertService.SingleOrDefaultAsync(m => m.ID == id);
            if (expertService == null)
            {
                return NotFound();
            }
            PopulateServiceTypeDropDownList(expertService.ServiceType);

            if (await _authorizationService.AuthorizeAsync(User, expertService, Operations.Update))
            {
                return View(expertService);
            }
            else
            {
                return new ChallengeResult();
            }
            
        }

        // POST: ExpertServices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Cost,MaxDaysToComplete,ServiceTypeID,Title,LongDescription,IsPublished,IsOpenForFunding")] ExpertService expertService)
        {
            if (id != expertService.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    expertService.ApplicationUserId = user;
                    _context.Update(expertService);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpertServiceExists(expertService.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", new { ID = id });
            }
            PopulateServiceTypeDropDownList(expertService.ServiceType);
            return View(expertService);
        }

        // GET: ExpertServices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expertService = await _context.ExpertService.SingleOrDefaultAsync(m => m.ID == id);
            if (expertService == null)
            {
                return NotFound();
            }

            return View(expertService);
        }

        // POST: ExpertServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var expertService = await _context.ExpertService.SingleOrDefaultAsync(m => m.ID == id);
            _context.ExpertService.Remove(expertService);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ExpertServiceExists(int id)
        {
            return _context.ExpertService.Any(e => e.ID == id);
        }

        public IActionResult Purchase()
        {

            return View();

        }
        [Authorize]
        public async Task<IActionResult> Invest(int? id)
        {
            //if user is not logged in, direct them to login or create account (with a redirect back to here) - should be automatic



            //if the user does not have an invention, direct them to create one (with a redirect back to here)
            //first we need to associate inventions with the active user. 
            //to start, lets just create an invention

            if (id == null)
            {
                return NotFound();
            }

            var expertService = await _context.ExpertService.Include(m => m.ServiceType).SingleOrDefaultAsync(m => m.ID == id);

            if (expertService == null)
            {
                return NotFound();
            }

            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            Invention invention = new Invention(); 

            invention.ApplicationUserId = user;
            invention.Title = User.Identity.Name +"'s Invention";
            invention.IsOpenForFunding = true;
            //this will result in 20% of the invention being allocated to the round
            invention.Valuation = expertService.Cost * 4;
            invention.IsPublished = true; 
            
            _context.Add(invention);
            _context.SaveChanges();

            //await _context.SaveChangesAsync();


            //if the user has multiple inventions, ask them to select which one, assume the last updated and give them an option to change

            //now add an investment round, with the expert service and the invention specified - create investment round and associate with invention and expert service

            InvestmentRound investmentRound = new InvestmentRound();
            investmentRound.ExpertServiceID = expertService.ID;

src/INV/Views/Inventions/Delete.cshtml
@model INV.Models.Invention

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invention</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsForSale)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsForSale)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/INV/Views/Inventions/Details.cshtml
@model INV.Models.Invention
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = Model.Title;
}

<h2>@Model.Title</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.UserName)
        </dt>
        <dd>
            @Html.ActionLink(Model.ApplicationUser.UserName, "Details", "ApplicationUsers", new { id = Model.ApplicationUserId }, null)
        </dd>
    </dl>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>
        <dd>
            @Html.Raw(Model.LongDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        @if (Model.IsForSale)
        {
            <dt>
                @Html.DisplayNameFor(model => model.IsForSale)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsForSale)
            </dd>
        }
        @*<dt>
                @Html.DisplayNameFor(model => model.IsOpenForFunding)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsOpenForFunding)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.IsPublished)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsPublished)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Valuation)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Valuation)
            </dd>*@

    </dl>
    <hr/>
    <h2> Promote This Invention:  </h2>
    @{
        var host = @Context.Request.Host;
        var twitterLink = @String.Format("https://twitter.com/home?status={0}%20{1}/Inventions/Details/{2}", Uri.EscapeDataString("Check out this invention: " + Model.Title), host, Model.ID);
        var linkedinLink = @String.Format("https://www.linkedin.com/shareArticle?mini=true&url={1}/Inventions/Details/{2}&title={0}&summary=&source=", Uri.EscapeDataString("Check out this invention: " + Model.Title), host, Model.ID);
        var facebookLink = @String.Format("https://www.facebook.com/sharer/sharer.php?u={1}/Inventions/Details/{2}", Uri.EscapeDataString("Check out this invention: " + Model.Title), host, Model.ID);
    }
    <a href="@twitterLink" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i> Share on Twitter</a> |
    <a href="@linkedinLink" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i> Share on LinkedIn</a> |
    <a href="@facebookLink" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i> Share on Facebook</a>


    @{
        //this handles open rounds
        if (Model.InvestmentRounds.Count > 0 && !SignInManager.IsSignedIn(User))
        {
            <br />
            <h2>Sign In Required</h2>
            <br />
            <span class="dl-horizontal alert alert-info">
                There is more information available for this invention, but you must be signed in to see it. You can <a asp-action="Login" asp-controller="Account" asp-route-returnurl="/Inventions/Details/@Model.ID">Create an Account or Log In</a> 
                to gain access to this additional information. 
            </span>
            <br /><br /><br /><br />
        }
        if (Model.InvestmentRounds.Count > 0 && SignInManager.IsSignedIn(User))
        {
            var openRoundCount = Model.InvestmentRounds.Where(ir => ir.IsOpenForFunding == true).Count();
            if (openRoundCount > 0 && Model.IsOpenForFunding == true)
            {

                InvestmentRound investmentRound = Model.InvestmentRounds.Where(ir => ir.IsOpenForFunding == true).First();
                if (TempData["invested"] != null && TempData["invested"].ToString() == "true")
                {
                    <h2>Want to Invest? </h2>
                    <dl class="dl-horizontal alert alert-info">
                        Awesome! Your request to invest is submitted, and you will be notified by the inventor if the round closes and you are part of it.
                    </dl>
                }
                else
                {


                    @if (investmentRound.Investments.Count > 0)
                {
                        <hr/>
                        <h2>Investor Team</h2>
                        <dl class="dl-horizontal">
                            <dt>
                                Investors
                            </dt>
                            @foreach (Investment i in investmentRound.Investments)
                {

                                <dd>

                                    @Html.ActionLink(i.ApplicationUser.UserName, "Details", "ApplicationUsers", new { id = i.ApplicationUserId }, null)

                                    @String.Format("{0:C}", i.InvestmentAmount)
                                    @*@Html.ActionLink(string.Format("Title: {0} | Open for Funding: {1}", i.Title, i.IsOpenForFunding), "Details", "InvestmentRounds", new { id = i.ID }, null)*@ &nbsp;
                                </dd>
                            }
                            <dt>
                                Total Committed
                            </dt>
                            <dd>
                                @String.Format("{0:C}", investmentRound.Investments.Sum(i => i.InvestmentAmount))
                            </dd>

                        </dl>
                    }
                    <hr />
                    <h2>Want to Invest? </h2>
                        <dl class="dl-horizontal alert alert-info">
                            <dt>
                                Inventor is Raising
                            </dt>
                            <dd>
                                @String.Format("{0:C}", investmentRound.RaiseAmount)
                                <br /><br />
                            </dd>
                            <dt>
                                Use of Funds
                            </dt>
                            <dd>
                                @*Logic: if this is DIY funding where inventor and expert id are equal AND the web visitor is not the inventor, do not link to the expertservice*@
                                @if (investmentRound.Invention.ApplicationUserId == investmentRound.ExpertService.ApplicationUserId && ViewData["isEditable"].ToString() != "true")
                                {
                                    @investmentRound.ExpertService.Title
                                    <text> (NOTE: this is a DIY service where the inventor is serving as his/her own expert)</text>

                                }
                                else
                                {
                                    @Html.ActionLink(investmentRound.ExpertService.Title, "Details", "ExpertServices", new { id = investmentRound.ExpertServiceID }, new { target = "_blank" })

                                }
                                <br /><br />

                            </dd>
                            <dt>
                                @{
                                    var hundredPercentofRound = investmentRound.RaiseAmount;
                                    var hundredPercentofRoundOwnership = hundredPercentofRound / (Model.Valuation + investmentRound.RaiseAmount);
                                }
                                Commit 100% of Round
                            </dt>
                            <dd>
                                @Html.ActionLink(string.Format("{0:C}", hundredPercentofRound), "Invest", "InvestmentRounds", new { id = investmentRound.ID, investmentAmount = Convert.ToInt64(hundredPercentofRound) }, new { @class = "btn btn-default btn-lg" })<br />
                                By clicking the button above, you are indicating you would like to invest up to @hundredPercentofRound, which represents @String.Format("{0:p}", hundredPercentofRoundOwnership) ownership of Invention. <br /><br />
                            </dd>

                            <dt>
                                @{
                                    var twentyFivePercentofRound = investmentRound.RaiseAmount / 4;
                                    var twentyFivePercentofRoundOwnership = twentyFivePercentofRound / (Model.Valuation + investmentRound.RaiseAmount);
                                }
                                Commit 25% of Round
                            </dt>
                            <dd>
                                @Html.ActionLink(string.Format("{0:C}", twentyFivePercentofRound), "Invest", "InvestmentRounds", new { id = investmentRound.ID, investmentAmount = Convert.ToInt64(twentyFivePercentofRound) }, new { @class = "btn btn-default btn-lg" })<br />
                                By clicking the button above, you are indicating you would like to invest up to @twentyFivePercentofRound, which represents @String.Format("{0:p}", twentyFivePercentofRoundOwnership) ownership of Invention.<br /><br />
                            </dd>

                            <dt>
                                @{
                                    var tenPercentofRound = investmentRound.RaiseAmount / 10;
                                    var tenPercentofRoundOwnership = tenPercentofRound / (Model.Valuation + investmentRound.RaiseAmount);
                                }
                                Commit 10%  of Round
                            </dt>
                            <dd>
                                @Html.ActionLink(string.Format("{0:C}", tenPercentofRound), "Invest", "InvestmentRounds", new { id = investmentRound.ID, investmentAmount = Convert.ToInt64(tenPercentofRound) }, new { @class = "btn btn-default btn-lg" })<br />
                                By clicking the button above, you are indicating you would like to invest up to @tenPercentofRound, which represents @String.Format("{0:p}", tenPercentofRoundOwnership) ownership of Invention.<br /><br />
                            </dd>
                            <dt>
                                @{
                                    var onePercentofRound = investmentRound.RaiseAmount / 100;
                                    var onePercentofRoundOwnership = onePercentofRound / (Model.Valuation + investmentRound.RaiseAmount);
                                }
                                Commit 1%  of Round
                            </dt>
                            <dd>
                                @Html.ActionLink(string.Format("{0:C}", onePercentofRound), "Invest", "InvestmentRounds", new { id = investmentRound.ID, investmentAmount = Convert.ToInt64(onePercentofRound) }, new { @class = "btn btn-default  btn-lg" })<br />

                                By clicking the button above, you are indicating you would like to invest up to @onePercentofRound, which represents @String.Format("{0:p}", onePercentofRoundOwnership) ownership of Invention.<br /><br />
                            </dd>
                            @if (ViewData["isEditable"].ToString() == "true")
                        {
                                <dt></dt>
                                <dd>

                                    @Html.ActionLink("Edit/Close Investment Round", "Edit", "InvestmentRounds", new { Id = investmentRound.ID })
                                </dd>


                            }
                        </dl>
            }
        }
    }



}



    @{
        //this handles past rounds
        var closedRoundCount = 0;
        if (Model.InvestmentRounds.Count > 0)
        {
            closedRoundCount = Model.InvestmentRounds.Where(ir => ir.IsOpenForFunding != true).Count();
        }
    }
    @if (closedRoundCount > 0)
    {
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Investment Round
            </dt>
            @foreach (InvestmentRound i in Model.InvestmentRounds)
            {

                <dd>
                    @Html.ActionLink(string.Format("Title: {0}", i.Title), "Details", "InvestmentRounds", new { id = i.ID }, null)
                </dd>
            }
        </dl>
    }
</div>

<div>

    @if (ViewData["isEditable"].ToString() == "true")
    {

        @Html.ActionLink("Edit Invention", "Edit", new { Id = Model.ID });
        <text> | </text>
    }
    <a asp-action="Index">Back to Inventions</a>
</div>