src/INV/Controllers/InventionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using INV.Data;
using INV.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using INV.Models.InventionViewModels;

namespace INV.Controllers
{
    public class InventionsController : Controller
    {
        IAuthorizationService _authorizationService;



        //bigtime dependency injection
        //private readonly UserManager<ApplicationUser> _userManager;

        private readonly ApplicationDbContext _context;

        public InventionsController(ApplicationDbContext context, IAuthorizationService authorizationService)
        {
            _context = context;
            _authorizationService = authorizationService;
        }

        // GET: Inventions
        public async Task<IActionResult> Index()
        {
            var mex = Environment.CurrentManagedThreadId; 
            ViewData["Title"] = "All Inventions";
            var invention = _context.Invention
                .Include(i => i.ApplicationUser)
                .Where(i => i.IsPublished)
                .OrderByDescending(i => i.DateCreated);

            return View("Index", await invention.ToListAsync());
        }

        // GET: Invest
        public async Task<IActionResult> Invest()
        {
            var invention = _context.Invention
                .Include(i=>i.ApplicationUser)
                .Where(i => i.IsOpenForFunding == true)
                //.Where(i=>i.AnotherIsOpenForFunding() == true)
                .Where(i => i.IsPublished)
                .OrderByDescending(i => i.DateCreated); 


            ViewData["Title"] = "Invest in Inventions";

            return View("Index", await invention.ToListAsync());
        }

        // GET: Buy
        public async Task<IActionResult> Buy()
        {
            var invention = _context.Invention
                .Include(i => i.ApplicationUser)
                .Where(i => i.IsForSale == true)
                .Where(i => i.IsPublished)
                .OrderByDescending(i => i.DateCreated)
                .AsNoTracking();
            ViewData["Title"] = "Buy Inventions";
            return View("Index", await invention.ToListAsync());
        }

        // GET: Inventions/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var invention = await _context.Invention
                .Include(i => i.InvestmentRounds) 
                .ThenInclude(ir=>ir.RoundStatus)
                .Include(i => i.InvestmentRounds)
                .ThenInclude(ir => ir.Investments)
                .ThenInclude(iv=>iv.ApplicationUser)
                .Include(i => i.InvestmentRounds)
                .ThenInclude(ir => ir.ExpertService)
                //this is the application user for the investment
                .ThenInclude(i=>i.ApplicationUser)
                .Include(i=>i.ApplicationUser)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (invention == null)
            {
                return NotFound();
            }
            ViewData["isEditable"] = "false";
            if (invention.ApplicationUserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                ViewData["isEditable"] = "true"; 
            }
            return View(invention); 
        }

        [Authorize]
        // GET: Inventions/Create
        public async Task<IActionResult> Create()
        {
            //we are seeing if the user has an invention already
            var invention = await _context.Invention
                .Include(i => i.ApplicationUser)
                .ThenInclude(au => au.Inventions)
                .Where(i=>i.ApplicationUserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
                .FirstOrDefaultAsync();
            if (invention!=null && invention.ApplicationUser!=null && invention.ApplicationUser.Inventions != null)
            {
                TempData["hasInventions"] = "true"; 
            }
            return View();
        }

        // POST: Inventions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,DateCreated,IsForSale,Title,IsOpenForFunding,LongDescription")] Invention invention)
        {
            

            if (ModelState.IsValid)
            {
                var user = User.FindFirst(ClaimTypes.NameIdentifier).Value; 
                invention.ApplicationUserId = user; 
                _context.Add(invention);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { ID = invention.ID });
            }
            return View(invention);
        }

        [Authorize]
        // GET: Inventions/CreateForSale
        public IActionResult CreateForSale()
        {
            TempData["ForSale"] = "true";
            return View("Create");
        }


        [Authorize]
        // GET: Inventions/CreateDIY
        public IActionResult CreateDIY()
        {
            return View();
        }

        // POST: Inventions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDIY([Bind("Invention.Title,Invention.LongDescription,Invention.Valuation,ExpertService.Title,ExpertService.Cost,ExpertService.MaxDaysToComplete")] InventionViewModel inventionCollection)
        {
            //two ways to chain: 1) add a couple or triple of models to a view controller, or 2) just chain them together with adds. Think #2 is better. 

            if (ModelState.IsValid)
            {

                var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Invention invention = new Invention();
                invention.Title = Request.Form["Invention.Title"];
                invention.LongDescription = Request.Form["Invention.LongDescription"];
                invention.Valuation = Convert.ToInt16(Request.Form["Invention.Valuation"]);
                invention.IsForSale = false;
                invention.IsOpenForFunding = true;
                invention.IsPublished = true;
                invention.ApplicationUserId = user; 
                inventionCollection.Invention = invention; 
                inventionCollection.Invention.ApplicationUserId = user;
                ExpertService expertService = new ExpertService();
                expertService.Title = Request.Form["ExpertService.Title"];
                expertService.IsPublished = false;
                expertService.LongDescription = "I will use the funding to work on my invention and to pay for expenses.";
                expertService.MaxDaysToComplete = Convert.ToInt16(Request.Form["ExpertService.MaxDaysToComplete"]);
                expertService.Cost = Convert.ToInt16(Request.Form["ExpertService.Cost"]);
                expertService.ServiceTypeID = 2;
                expertService.ApplicationUserId = user; 
                inventionCollection.ExpertService = expertService; 
                _context.Add(invention);
                _context.Add(expertService);
                _context.SaveChanges();
                InvestmentRound investmentRound = new InvestmentRound();
                investmentRound.InventionID = invention.ID;
                investmentRound.RaiseAmount = expertService.Cost;
                investmentRound.Title = "DIY Round";
                investmentRound.IsOpenForFunding = true;
                investmentRound.ExpertServiceID = expertService.ID;
                investmentRound.RoundStatusID = 1; 
                _context.Add(investmentRound);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { ID = inventionCollection.Invention.ID });
            }
            return View(inventionCollection);
        }


        // GET: Inventions/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invention = await _context
                .Invention
                .Include(m=>m.InvestmentRounds)
                .ThenInclude(ir=>ir.ExpertService)
                .ThenInclude(es=>es.ServiceType)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (invention == null)
            {
                return NotFound();
            }

            if (await _authorizationService.AuthorizeAsync(User, invention, Operations.Update))
            {
                ViewData["Title"] = "Describe " + invention.Title;
                if (TempData["isNew"] != null)
                {
                    invention.Title = "";
                }
                //lets see if there is an open investment round to set IsOpenForFunding
                if (invention.InvestmentRounds != null && invention.InvestmentRounds.Where(ir => ir.IsOpenForFunding).Count() > 0)
                {
                    invention.IsOpenForFunding = true;
                }
                else if ((invention.InvestmentRounds == null) || (invention.InvestmentRounds.Where(ir => ir.IsOpenForFunding).Count() == 0)) 
                {

src/INV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventose</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <script src="https://use.fontawesome.com/1e50e9f921.js"></script>
          
        

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />*@

        <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
        <script src="https://use.fontawesome.com/1e50e9f921.js"></script>
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Inventose</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="ExpertServices" asp-action="Index">Find Experts</a></li>
                    @*<li><a asp-area="" asp-controller="ExpertServices" asp-action="Patent">Find Patent Attorney</a></li>
                    <li><a asp-area="" asp-controller="ExpertServices" asp-action="Prototype">Find Prototype Builder</a></li>*@
                    <li><a asp-area="" asp-controller="Inventions" asp-action="Invest">Invest in Invention</a></li>
                    <li><a asp-area="" asp-controller="Inventions" asp-action="CreateForSale">Sell Invention</a></li>

                    <li><a asp-area="" asp-controller="Inventions" asp-action="Buy">Buy Invention</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (@TempData["message"] != null)
        {
        <span class="alert alert-success" style="color:green; font-size:14px; line-height:12px">@TempData["message"]</span> 
        }
        @RenderBody()
        <hr />
        <footer>
            <p>Email <a href="mailto:matt@dyor.com">Matt@Dyor.com</a> for any problems, suggestions, or just to chat about your invention <br/> Site last updated: 
            <script language="javascript">
                var date = new Date('@System.IO.File.GetLastWriteTime("views/shared/_layout.cshtml") UTC');
                document.write(date.toString());
                //alert('@System.IO.File.GetLastWriteTime("views/shared/_layout.cshtml") UTC');
            </script>  &copy; 2017 </p> 
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        @*<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>*@
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    
    @RenderSection("scripts", required: false)
</body>
</html>

src/INV/Views/Shared/_LongDescriptionPartial.cshtml
<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.1.7/quill.snow.css" rel="stylesheet">
<style>
    .ql-snow {
        width: 550px;
    }
</style>
<!-- Create the editor container -->
<div id="LongDescriptionShadow" style="height:200px; width:550px"></div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.1.7/quill.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        var ldText = $("#LongDescription").val();

        quill.pasteHTML(0, ldText, '', true);
        //keep hiddent text field in sync with Quill content
        quill.on('text-change', function (delta, source) {
            $("#LongDescription").val($(".ql-editor").html());
        });
        //prevent Quill controls from receiving tab focus
        $(".ql-toolbar").find(":button").attr('tabindex', '-1');

    });
</script>
<!-- Initialize Quill editor -->
<script>
    var toolbarOptions = [
        ['bold', 'italic', 'underline', 'strike'],
        ['blockquote', 'code-block'],
        [{ 'header': 1 }, { 'header': 2 }],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'indent': '-1' }, { 'indent': '+1' }],
        [{ 'direction': 'rtl' }],
        ['link', 'image']
    ];
    //keyboard module prevents tabbing in Quill, and instead tabs to next field
    var quill = new Quill('#LongDescriptionShadow', {
        modules: {
            toolbar: toolbarOptions,
            keyboard: {
                bindings: {
                    tab: {
                        key: 9,
                        handler: function () {
                            var inputs = $("#LongDescriptionShadow").closest('form').find(':input');
                            inputs.eq(inputs.index(this) + 19).focus();
                        }
                    }
                }
            },
        },

        theme: 'snow'
    });
</script>