src/INV/Models/InvestmentRound.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace INV.Models
{
    public class InvestmentRound
    {
        public int ID { get; set;  }
        public string Title { get; set;  }
        public virtual Invention Invention { get; set; }
        public int InventionID { get; set; }
        [Display(Name = "Expert Service")]
        public virtual ExpertService ExpertService { get; set;  }
        public int ExpertServiceID { get; set;  }
        
        public virtual ICollection<Investment> Investments { get; set; }
        [Display(Name = "Date Created")]
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; } = DateTime.Now;
        [Display(Name ="Is Open for Funding?")]
        public Boolean IsOpenForFunding { get; set; }

        public virtual RoundStatus RoundStatus { get; set;  }

        public int RoundStatusID { get; set;  }

        //flow is : Open, Subscribed (enough cash has been pledged), FundingSettled (full amount of capital received), ServiceSettled (capital sent to expert after completion of service)

        [DataType(DataType.Currency)]
        public Decimal RaiseAmount { get; set;  }

    }
}

src/INV/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using INV.Data;
using INV.Models;
using System.Security.Claims;

namespace INV.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationUsersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.ToListAsync());
        }

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string user = "";
            if (User.Identity.Name != null)
            {
                user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            ApplicationUser applicationUser = await _context
                .ApplicationUser
                .Include(au => au.Inventions)
                .Include(au => au.Investments)
                .Include(au => au.ExpertServices)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (id == user)
            {
                ViewData["isEditable"] = "true";
                
            }
  

            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AccessFailedCount,ConcurrencyStamp,Email,EmailConfirmed,LinkedInURL,LockoutEnabled,LockoutEnd,LongDescription,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwitterURL,TwoFactorEnabled,UserName,WebAddress,YouTubeIntro,FirstName,LastName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                applicationUser.NormalizedEmail = applicationUser.Email; 
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AccessFailedCount,ConcurrencyStamp,Email,EmailConfirmed,LinkedInURL,LockoutEnabled,LockoutEnd,LongDescription,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwitterURL,TwoFactorEnabled,UserName,WebAddress,YouTubeIntro,FirstName,LastName")] ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    applicationUser.NormalizedEmail = applicationUser.Email;
                    _context.Update(applicationUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { Id = id });
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

src/INV/Controllers/InvestmentRoundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using INV.Data;
using INV.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace INV.Controllers
{
    public class InvestmentRoundsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InvestmentRoundsController(ApplicationDbContext context)
        {
            _context = context;    
        }



        // GET: InvestmentRounds
        public async Task<IActionResult> Index()
        {
            var investmentRounds = _context.InvestmentRound
                .Include(ir => ir.Invention)
                .Include(ir => ir.ExpertService)
                .AsNoTracking();
            return View(await investmentRounds.ToListAsync());
        }

        // GET: InvestmentRounds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investmentRound = await 
                _context.InvestmentRound
                .Include(m=>m.Invention)
                .ThenInclude(i=>i.ApplicationUser)
                .Include(m=>m.ExpertService)
                .Include(m=>m.Investments)
                .ThenInclude(ir=>ir.ApplicationUser)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (investmentRound == null)
            {
                return NotFound();
            }
            ViewData["isEditable"] = "false";
            if (investmentRound.Invention.ApplicationUserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                ViewData["isEditable"] = "true";
            }

            return View(investmentRound);
        }

        // GET: InvestmentRounds/Create
        public IActionResult Create()
        {
            PopulateInventionDropDownList();
            PopulateExpertServiceDropDownList();
            return View();
        }

        // POST: InvestmentRounds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,DateCreated,Title,InventionID,ExpertServiceID, IsOpenForFunding")] InvestmentRound investmentRound)
        {
            if (ModelState.IsValid)
            {
                _context.Add(investmentRound);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            PopulateInventionDropDownList(investmentRound.Invention);
            PopulateExpertServiceDropDownList(investmentRound.ExpertService); 
            return View(investmentRound);
        }

        // GET: InvestmentRounds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investmentRound = await _context.InvestmentRound.SingleOrDefaultAsync(m => m.ID == id);
            if (investmentRound == null)
            {
                return NotFound();
            }
            PopulateInventionDropDownList(investmentRound.Invention);
            PopulateExpertServiceDropDownList(investmentRound.ExpertService); 
            return View(investmentRound);
        }

        // POST: InvestmentRounds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,DateCreated,Title,RaiseAmount,IsOpenForFunding")] InvestmentRound investmentRound)
        {
            if (id != investmentRound.ID)
            {
                return NotFound();
            }
            var investmentRoundOriginal = _context.InvestmentRound.Single(m => m.ID == id);

            if (ModelState.IsValid)
            {
                try
                {
                    //we just want to update updateable fields
                    investmentRoundOriginal.Title = investmentRound.Title;
                    investmentRoundOriginal.RaiseAmount = investmentRound.RaiseAmount;
                    investmentRoundOriginal.IsOpenForFunding = investmentRound.IsOpenForFunding;



                    _context.Update(investmentRoundOriginal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvestmentRoundExists(investmentRound.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Inventions", new { ID = investmentRoundOriginal.InventionID });
            }
            PopulateInventionDropDownList(investmentRound.Invention);
            return View(investmentRound);
        }

        private void PopulateInventionDropDownList(object selectedInvention = null)
        {
            ViewBag.InventionID = new SelectList(_context.Invention.OrderBy(i => i.Title).AsNoTracking(), "ID", "Title", selectedInvention);            
        }

        private void PopulateExpertServiceDropDownList(object selectedExpertService = null)
        {
            ViewBag.ExpertServiceID = new SelectList(_context.ExpertService.OrderBy(i => i.Title).AsNoTracking(), "ID", "Title", selectedExpertService);
        }

        // GET: InvestmentRounds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investmentRound = await _context.InvestmentRound.SingleOrDefaultAsync(m => m.ID == id);
            if (investmentRound == null)
            {
                return NotFound();
            }

            return View(investmentRound);
        }

        // POST: InvestmentRounds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var investmentRound = await _context.InvestmentRound.SingleOrDefaultAsync(m => m.ID == id);
            _context.InvestmentRound.Remove(investmentRound);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> Invest (int id, [FromQuery]int investmentAmount)
        {
            //we need to create an investment that is associated with this investment round and with the active user

            var investmentRound = await _context.InvestmentRound.SingleOrDefaultAsync(m => m.ID == id);

            if (investmentRound == null)
            {
                return NotFound();
            }

            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            Investment investment = new Investment();
            //Invention invention = new Invention();
            investment.ApplicationUserId = user;
            investment.InvestmentRound = investmentRound;
            investment.InvestmentAmount = investmentAmount; 
            _context.Add(investment);
            _context.SaveChanges();
            TempData["invested"] = "true";
            //TempData["message"] = "Awesome! Your request to invest is submitted, and you will be notified by the inventor if the round closes and you are part of it. ";
            return RedirectToAction("Details", "Inventions", new { ID = investmentRound.InventionID});

        }

        private bool InvestmentRoundExists(int id)
        {
            return _context.InvestmentRound.Any(e => e.ID == id);
        }
    }
}

src/INV/Views/InvestmentRounds/Create.cshtml
@model INV.Models.InvestmentRound

@*@{
    ViewData["Title"] = "Create";
}*@

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>InvestmentRound</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="DateCreated" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Invention" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="InventionID" class="form-control" asp-items="ViewBag.InventionID">
                    <option value="">-- Select Invention --</option>
                </select>
                <span asp-validation-for="Invention" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ExpertService" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ExpertServiceID" class="form-control" asp-items="ViewBag.ExpertServiceID">
                    <option value="">-- Select Expert Service --</option>
                </select>
                <span asp-validation-for="ExpertService" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/INV/Views/InvestmentRounds/Delete.cshtml
@model INV.Models.InvestmentRound

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InvestmentRound</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/INV/Views/InvestmentRounds/Details.cshtml
@model INV.Models.InvestmentRound

@{
    ViewData["Title"] = "Details";
}

<h2>Investment Round Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Invention.Title)
        </dt>
        <dd>
            @Html.ActionLink(Model.Invention.Title, "Details", "Inventions", new { id = Model.InventionID }, null)
        </dd>
    </dl>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Invention.ApplicationUser.UserName)
        </dt>
        <dd>
            @Html.ActionLink(Model.Invention.ApplicationUser.UserName, "Details", "ApplicationUsers", new { id = Model.Invention.ApplicationUserId }, null)
        </dd>
    </dl>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExpertService.Title)
        </dt>
        <dd>
            @Html.ActionLink(Model.ExpertService.Title, "Details", "ExpertServices", new {  id = Model.ExpertServiceID})
            
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RaiseAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RaiseAmount)
        </dd>
        </dl>
    <hr />
        
    <dl class="dl-horizontal">
        <dt>
            Investors
        </dt>
        @if (Model.Investments.Count == 0)
        {
            <dd>
                This round does not have any investors. 
                @if (ViewData["isEditable"].ToString() == "true")
                {
                    <text>
                    You can either <a asp-action='Delete' asp-route-id='@Model.ID'>Delete</a>  or <a asp-action='Edit' asp-route-id='@Model.ID'>Reopen</a> this round.
                    </text>
                }
            </dd>
        }
        @foreach (Investment i in Model.Investments)
        {

            <dd>
                @i.ApplicationUser.UserName

                @i.InvestmentAmount
                @*@Html.ActionLink(string.Format("Title: {0} | Open for Funding: {1}", i.Title, i.IsOpenForFunding), "Details", "InvestmentRounds", new { id = i.ID }, null)*@
            </dd>
        }
    </dl>
</div>
<div>
@if (ViewData["isEditable"].ToString() == "true")
{
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> 
}
</div>

src/INV/Views/InvestmentRounds/Edit.cshtml
@model INV.Models.InvestmentRound

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>InvestmentRound</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        @*<div class="form-group">
            <label asp-for="DateCreated" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger" />
            </div>
        </div>*@
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        @*<div class="form-group">
            <label asp-for="Invention" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="InventionID" class="form-control" asp-items="ViewBag.InventionID">
                    <option value="">-- Select Invention --</option>
                </select>
                <span asp-validation-for="Invention" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ExpertService" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ExpertServiceID" class="form-control" asp-items="ViewBag.ExpertServiceID">
                    <option value="">-- Select Expert Service --</option>
                </select>
                <span asp-validation-for="ExpertService" class="text-danger" />
            </div>
        </div>*@
        @*xxx<div class="form-group">
            <label asp-for="RoundStatus" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="RoundStatusID" class="form-control" asp-items="ViewBag.RounderServiceID">
                    <option value="">-- Select Expert Service --</option>
                </select>
                <span asp-validation-for="ExpertService" class="text-danger" />
            </div>
        </div>*@
        <div class="form-group">
            <label asp-for="RaiseAmount" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="RaiseAmount" class="form-control" />
                <span asp-validation-for="RaiseAmount" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsOpenForFunding" />
                    <label asp-for="IsOpenForFunding"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Delete" asp-route-id="@Model.ID">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/INV/Views/InvestmentRounds/Index.cshtml
@model IEnumerable<INV.Models.InvestmentRound>

@{
    ViewData["Title"] = "Index";
}

<h2>Investment Rounds</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invention)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invention.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>